### ISSUE TITLE
make: g++: Command not found

### ISSUE THREAD

**Issue by karencho777** [uPlexa/uplexa-gui#1]
hello, I wanna install the miner, but here is the errors...

`$ ./build.sh
Building release
~/uplexa-gui ~/uplexa-gui
~/uplexa-gui ~/uplexa-gui
D       include/INode.h
D       include/IWallet.h
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
~/uplexa-gui/uplexa ~/uplexa-gui ~/uplexa-gui
You are currently on commit e7dd3be6
The most recent tag was at 2b635ae5
You are ahead of or behind a tagged release
~/uplexa-gui ~/uplexa-gui
D       include/INode.h
D       include/IWallet.h
Switched to and reset branch 'e7dd3be6'
libwallet_merged.a not found - Building libwallet
Building libwallet release
cleaning up existing uplexa build dir, libs and includes
~/uplexa-gui/uplexa/build/release ~/uplexa-gui ~/uplexa-gui
Unknown platform, configuring general build
./get_libwallet_api.sh: line 205: cmake: command not found
./get_libwallet_api.sh: line 216: pushd: /home/User/uplexa-gui/uplexa/build/release/src/wallet: No such file or directory
make: Entering directory '/home/User/uplexa-gui/uplexa'
cat version.sh >version
chmod a+x version
make: Leaving directory '/home/User/uplexa-gui/uplexa'
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
~/uplexa-gui ~/uplexa-gui
./get_libwallet_api.sh: line 225: pushd: /home/User/uplexa-gui/uplexa/build/release/src/daemon: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
~/uplexa-gui
make: *** /home/User/uplexa-gui/uplexa/build/release/contrib/epee: No such file or directory.  Stop.
make: *** /home/User/uplexa-gui/uplexa/build/release/external/easylogging++: No such file or directory.  Stop.
make: *** /home/User/uplexa-gui/uplexa/build/release/external/db_drivers/liblmdb: No such file or directory.  Stop.
Installing libunbound...
./get_libwallet_api.sh: line 242: pushd: /home/User/uplexa-gui/uplexa/build/release/external/unbound: No such file or directory
make: *** No rule to make target 'install'.  Stop.
./get_libwallet_api.sh: line 246: popd: directory stack empty
./get_libwallet_api.sh: line 249: popd: directory stack empty
make: Entering directory '/home/User/uplexa-gui/src/zxcvbn-c'
g++ -I. -std=c++11 -O2 -Wall -Wextra \
        -o dictgen dict-generate.cpp
make: g++: Command not found
make: *** [makefile:61: dictgen] Error 127
make: Leaving directory '/home/User/uplexa-gui/src/zxcvbn-c'
`

**Comment by karencho777** [comment]
please no one can help?

**Comment by uPlexa** [comment]
You need to install cmake (compiler). Also, this is a wallet, not a miner.
